made fuctorial function
js-tasks-ru/jsbasic-20210906-2_pryadchenkor pull request #2
Opened 2021-09-10 08:42 UTC by RobertUkr

2021-09-10 08:43 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-10 10:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-10 11:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-10 13:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-10 14:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-11 17:25 UTC, SinimaWath requested changes

2021-09-11 17:25 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  let result = n;
В этом случае, можно не создавать переменную result. Это можно сделать, после условия `if (n === 0 || n === 1)`

2021-09-11 17:25 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  let result = n;
Так как она может не использоваться в условии `n === 0 || n === 1`

2021-09-11 17:25 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return name !== null ....`

Это как раз тот случай

2021-09-11 17:25 UTC, SinimaWath commented on 1-module/4-task/index.js
>  }
includes - возвращает boolean, поэтому можно обойтись без if:

`return newStr.includes(...) || newStr.includes(...)`

2021-09-11 17:25 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  newStr = str.toLowerCase();
Это неправильное создание переменной. На лекции обьяснял, что такая запись неявно пишет в глобальный обьект.

Используй тут const/let

2021-09-13 07:23 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-13 07:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-13 08:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-13 20:06 UTC, SinimaWath approved these changes
Все круто

2021-09-13 20:06 UTC, merged