Task 4
js-tasks-ru/jsbasic-20210906-2_pryadchenkor pull request #4
Opened 2021-09-16 15:25 UTC by RobertUkr

2021-09-16 15:26 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-16 20:04 UTC, SinimaWath requested changes

2021-09-16 20:04 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    .map((user, index) => index ? `\n${user.name}, ${user.balance}` : `${user.name}, ${user.balance}` )
Давай отсюда уберем `\n`.

И добавь его в join('\n') -  метод как раз и нужен для этого

2021-09-21 07:11 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-22 14:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-22 15:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-23 12:15 UTC, SinimaWath requested changes

2021-09-23 12:15 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  const tableRow = tabdiagonalRedle.getElementsByTagName("tr");
У тебя не проходят тесты в этой задаче. Давай попробуем их поправить

2021-09-27 14:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-27 14:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-27 15:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-27 17:05 UTC, SinimaWath approved these changes
все ок!

2021-09-27 17:06 UTC, merged